### ISSUE TITLE
AI improvements

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#200]
- [x] React better to confusion gas
- [x] Engagement distance #20
- [ ] Squads #21
- [ ] Stealth #22
- [ ] Better movement/targeting #23
- [x] Avoid explosions, flames / gasses (cover/evasion) #24 
- [ ] Patrolling #25 
- [x] Chatter #188 
- [ ] Pathfinding for fleeing #194 
- [x] Pathfinding around dangerous objects - go around or shoot?
- [x] Keep distance from player - to avoid blocking the player
##

**Comment by cxong** [comment]
All subitems have their own issues so no need for this issue anymore
