### ISSUE TITLE
Networked multiplayer

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#36]
Subtasks for a huge piece of work:

- [x] Networked input device (#220)
- [x] Refactor all game state changes as events (#225)
- [x] Spectators - client as total slave, accept all state changes from a server (#37)
- [x] Simple LAN multiplayer where clients are total slaves (no local simulation) #293 

After the simple LAN multiplayer, testing over a WAN (or with [simulated latency/loss](http://stackoverflow.com/questions/130354/how-do-i-simulate-a-low-bandwidth-high-latency-environment)) might reveal severe shortcomings in the protocol, such as

- [x] ~~Retransmissions and sequence numbers, ACKs~~
- [x] ~~Key-frames and delta frames~~

**Comment by cxong** [comment]
Clients will need to receive mission data from the server. For static maps this is not a problem, but for random maps it is. There are two alternatives:

- Create a new protocol that sends a map as-is, regardless of how it was generated
- Use a consistent PRNG

The second one is less work; here's a source for implementing a PRNG: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf

**Comment by cxong** [comment]
Basic low-latency multiplayer implemented; remaining tasks split to #384
