### ISSUE TITLE
Implement Cyberdogs gameplay

### ISSUE THREAD

**Issue by cxong** [cxong/cdogs-sdl#71]
There seems to be lots of fans of Cyberdogs, some who prefer its gameplay over C-Dogs. It'll be nice if its gameplay can be included in C-Dogs as well.

This is a pretty big feature composing many parts, so this should be split if it is ever undertaken:
- [x] Cyberdogs weapons (#268)
- [x] Armor (#219), buy/sell
- [x] Ammo (#278)
- [x] Lives (#741)
- [x] Auto melee (#742)
- [x] Buy/sell weapons/gear between levels (#739)
- [x] Buy/sell lives, max health (#757)
- [x] Upgradable weapons (for the chainguns) (#740)
- [x] Health bar (#26)
- [x] Animated tiles (big fans on ground) (#430, convert drains to map objects, animated tiles will be map objects instead, just like the drains)
- [ ] ~Additional stats in brief/debrief (% enemies, accuracy, enemies killed per weapon type)~
- [x] Weapon/ammo/gear pickups
- [x] Move while shooting (configurable), strafing button (#144)
- [x] Split screen options, including never (#137)
- [x] No weapon pushback (#146)
- [x] Rooms with no doors (just open spaces)
- [x] Mission complete message (#198)
- [x] Transition effect between game screens (#199)

**Comment by cxong** [comment]
Cyberdogs has the following enemies:

https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L372-L453

| Name      | Body  | Face       | Tracking | Moving | Shooting | Delay | Speed | Armor | Melee | Gun      |
|-----------|-------|------------|----------|--------|----------|-------|-------|-------|-------|----------|
| Default   | Brown | Grunt      | 10       | 10     | 2        | 25    | 6     | 15    | ?     | ?        |
| Killer    | Red   | Grunt2     | 15       | 15     | 2        | 20    | 12    | 10    | 1     | GoonGun2 |
| Robot     | Grey  | MechGrunt  | 15       | 15     | 5        | 25    | 4     | 20    | 1     | GoonGun3 |
| LittleBad | Black | Grunt2     | 15       | 15     | 1        | 10    | 16    | 10    | 2     | GoonGun2 |
| MeanGoon  | Brown | BlondGrunt | 15       | 15     | 5        | 15    | 8     | 15    | 1     | GoonGun2 |
| BigBad    | Black | BigBadGuy  | 10       | 10     | 5        | 10    | 8     | 20    | 3     | GoonGun4 |

**Comment by cxong** [comment]
Scoring

- Objects are worth 200 each
- Kills are worth 50 each
- Demolition bonus (?)
- Accuracy bonus (?)
- Time bonus (?)
- Ninja bonus (?)

**Comment by cxong** [comment]
![image](https://user-images.githubusercontent.com/1083215/229499142-cf4f2a87-a2f9-4f6e-90c2-4ad8083ca525.png)
![image](https://user-images.githubusercontent.com/1083215/229499206-a7a57d5a-a184-442c-b195-7c1d3b247f1a.png)
![image](https://user-images.githubusercontent.com/1083215/229499273-27a25328-6c91-49c4-b041-6ba8ede9fe31.png)
![image](https://user-images.githubusercontent.com/1083215/229499369-839ff2f0-5e1e-45a9-b134-0426e88978fb.png)
![image](https://user-images.githubusercontent.com/1083215/229499429-5d16c248-4921-4257-a7ad-2ce2b41eda8d.png)
![image](https://user-images.githubusercontent.com/1083215/229499541-eb61b589-2adb-4d43-8010-2b7afb27c8dd.png)
![image](https://user-images.githubusercontent.com/1083215/229499607-75579b34-da7e-4d16-a461-a117aa520a8e.png)
![image](https://user-images.githubusercontent.com/1083215/229499699-f7afd90a-ee42-48a6-806f-63b7e6d01b33.png)
![image](https://user-images.githubusercontent.com/1083215/229499759-086aff0d-ef43-4686-89b3-fb3a91ac4623.png)
![image](https://user-images.githubusercontent.com/1083215/229499817-d60c7e0f-53e7-4b53-82b3-c663fb39164f.png)

**Comment by cxong** [comment]
<html>
<body>

Mission | Objects | Kills | Destroy | Deadline | <img src="https://user-images.githubusercontent.com/1083215/227935924-db8c5aa0-6213-409c-bb67-c863f55fc8f7.png"/> | <img src="https://user-images.githubusercontent.com/1083215/227936170-69025a94-c7c3-42c6-8e2c-d5f8dbd2a1ff.png"/> | <img src="https://user-images.githubusercontent.com/1083215/227936571-e58fb4fd-098e-4878-a397-0ee33e39b575.png"/> | <img src="https://user-images.githubusercontent.com/1083215/227936406-47e4d646-7d9f-4c3d-a134-8a48b67d14b5.png"/>| <img src="https://user-images.githubusercontent.com/1083215/227936760-2fe4962d-de7e-46f4-9351-2a5afa31fff0.png"/> | <img src="https://user-images.githubusercontent.com/1083215/227936914-17ab6b75-3917-4770-917f-a8c8069802a2.png"/> | Wall | Floor
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 6 |   |   | 1:30 | 100% |   |   |   |   |   | ![image](https://user-images.githubusercontent.com/1083215/229503260-e8910d3b-8559-4937-8d5d-449ee1f3f329.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)
2 | 8 |   |   | 1:50 | 90% | 10% |   |   |   |   | ![image](https://user-images.githubusercontent.com/1083215/229503337-32cfdc52-566b-4153-a207-ff0591446164.png) | ![image](https://user-images.githubusercontent.com/1083215/229503195-254e014f-93cb-4508-848e-7f1f72a59153.png)
3 | 10 |   |   | 2:10 | 80% | 20% |   |   |   |   | ![image](https://user-images.githubusercontent.com/1083215/229503493-cac46dd9-4d7e-4056-9019-92e87ddbaa99.png) | ![image](https://user-images.githubusercontent.com/1083215/229502863-2ad430db-6a53-4c5a-ae8d-06b1d5789523.png)
4 | 12 |   |   | 2:30 | 70% | 15% | 15% |   |   |   | ![image](https://user-images.githubusercontent.com/1083215/229503493-cac46dd9-4d7e-4056-9019-92e87ddbaa99.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)
5 |   | 70 | 1 | 4:20 | 60% | 40% |   |   |   |   | ![image](https://user-images.githubusercontent.com/1083215/229503493-cac46dd9-4d7e-4056-9019-92e87ddbaa99.png) | ![image](https://user-images.githubusercontent.com/1083215/229502863-2ad430db-6a53-4c5a-ae8d-06b1d5789523.png)
6 | 8 | 40 |   | 3:50 | 50% | 16% |   | 16% | 16% |   | ![image](https://user-images.githubusercontent.com/1083215/229503493-cac46dd9-4d7e-4056-9019-92e87ddbaa99.png) | ![image](https://user-images.githubusercontent.com/1083215/229502863-2ad430db-6a53-4c5a-ae8d-06b1d5789523.png)
7 | 18 |   | 2 | 4:10 | 40% |   |   | 30% | 30% |   | ![image](https://user-images.githubusercontent.com/1083215/229503337-32cfdc52-566b-4153-a207-ff0591446164.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)
8 |   | 100 | 2 | 6:10 | 30% | 14% | 14% | 14% | 14% | 14% | ![image](https://user-images.githubusercontent.com/1083215/229503337-32cfdc52-566b-4153-a207-ff0591446164.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)
9 | 22 |   |   | 4:10 | 20% |   |   | 40% | 40% |   | ![image](https://user-images.githubusercontent.com/1083215/229503337-32cfdc52-566b-4153-a207-ff0591446164.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)
10 | 24 |   |   | 4:30 | 10% | 18% | 18% | 18% | 18% | 18% | ![image](https://user-images.githubusercontent.com/1083215/229503337-32cfdc52-566b-4153-a207-ff0591446164.png) | ![image](https://user-images.githubusercontent.com/1083215/229503036-53f88d83-7f4d-4202-84ce-085ef8bb82d9.png)

</body>
</html>

**Comment by cxong** [comment]
Mission maps (partial)

![image](https://user-images.githubusercontent.com/1083215/229800983-3193fc8b-a91f-4d6f-a927-5100c3ca4969.png)
![image](https://user-images.githubusercontent.com/1083215/229801123-f8b7b303-3a69-40db-80e4-ccd4e1b7046f.png)
![image](https://user-images.githubusercontent.com/1083215/229801374-b988bd75-81b8-47df-a5e0-a86e50bd450e.png)
![image](https://user-images.githubusercontent.com/1083215/229801576-221ae67a-1fc3-4c8e-a1bb-547b07188887.png)
![image](https://user-images.githubusercontent.com/1083215/229801769-da50267f-1b0b-44bb-8828-febeccd9d411.png)
![image](https://user-images.githubusercontent.com/1083215/229802248-35db41d3-7ba8-41d8-ae36-44b10febfb0d.png)
![image](https://user-images.githubusercontent.com/1083215/229802353-e5f38445-50d0-4f1c-8da9-e951490c5649.png)
![image](https://user-images.githubusercontent.com/1083215/229802524-7bdd2a63-565a-4b43-b3e2-6bf65c1c24c2.png)
![image](https://user-images.githubusercontent.com/1083215/229802625-068cfb3a-2924-4358-846f-8c82f910b8ab.png)
![image](https://user-images.githubusercontent.com/1083215/229802781-775bca05-3e6c-48f0-acbf-f611fa7bdc74.png)

Some notes:
- It feels like most maps are roughly square, although there may be slight differences in size
- Maps are composed of rooms with random number of doorways and random wall sections, similar to C-Dogs
- Objects are placed randomly but never against a wall, however they could block a doorway and can be placed side-by-side to each other
- Random debris (bullet holes, blood) seems to be splattered everywhere regardless of level
- Pickup objectives can appear anywhere
- Destroy objectives only occur in rooms

**Comment by cxong** [comment]
According to the source code, https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/dogs.pas#L479-L483 the map generation params may just be completely randomised

**Comment by cxong** [comment]
Reverse engineered weapon damage

 Gun | Damage
--- | ---
Blaster | 10
Powergun | 60
Flamer | 12
Minigun | 12
Launcher | 40
Megagun | 200

**Comment by cxong** [comment]
Raw info of weapon damage and missions
https://docs.google.com/spreadsheets/d/e/2PACX-1vQZq6FcXtlKnuURN8lJY3cnw3nz5oP877EBbIlzzHVzWGslbxQqeFsxt9wnbreHN9dPg994jwnEUQAi/pubhtml

**Comment by cxong** [comment]
Estimating from the minimap size, maps are 100x100

**Comment by cxong** [comment]
Demolition bonus is basically just the score you get for destroying items
It is equal to the health of the objects
https://github.com/cxong/cyberdogs/blob/dc536cecae07e1e7361278a2147fd567382bce93/game.pas#L692-L704
However this bonus, divided by 10, goes towards the end of level bonuses (whose calculation is unknown)

**Comment by cxong** [comment]
The way cyberdogs does demolition bonus is somewhat incompatible with C-Dogs.
C-Dogs gives score for damage inflicted on enemies, but not objects, unless that object is an objective, in which case a flat score is given when it is fully destroyed. However Cyberdogs adds score by damage, as if they were C-Dogs enemies.
As an approximation we can make Cyberdogs objects all objectives, however we'd need to add a way of customising score so that you get more points for tougher objects.

**Comment by cxong** [comment]
Mission | Pickups
--- | ---
1 | Powergun
2 | Powergun, max armor
3 | armorx2
4 | max armor
5 | armorx3
6 | max armor, armorx2
7 | armorx3, max armorx2
8 | armorx3, max armor, flamer
9 | armorx4, powergun
10 | max armorx2, armorx2

**Comment by cxong** [comment]
Gun | Bullet | Colour | Speed | Range | Damage
--- | --- | --- | --- | --- | --- 
DumbGun | laser_dumb | red | 384 | 110 | 5
Lazer | laser | yellow | 960 | 100 | 10
Gun | pulse_green | green | 768 | 110 | 3
TurboLazer | turbo_laser | yellow | 960 | 100 | 8

**Comment by cxong** [comment]
Gun rates

Gun | Rate
--- | --- 
PowerGun | 40
Blaster | 12
MiniGun | 7
Flamer | 7
Launcher | 30
DumbGun | 40
Gun | 30
Lazer | 65
TurboLazer | 35
Zapper | 7
